# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class DutchieProducerItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    Producer_ID = scrapy.Field()
    Producer = scrapy.Field()
    Description = scrapy.Field()
    Link = scrapy.Field()
    SKU = scrapy.Field()
    City = scrapy.Field()
    Province = scrapy.Field()
    ccc = scrapy.Field()
    Page_Url = scrapy.Field()
    Active = scrapy.Field()
    Main_image = scrapy.Field()
    Image_2 = scrapy.Field()
    Image_3 = scrapy.Field()
    Image_4 = scrapy.Field()
    Image_5 = scrapy.Field()
    Type = scrapy.Field()
    License_Type = scrapy.Field()
    Date_Licensed = scrapy.Field()
    Phone = scrapy.Field()
    Phone_2 = scrapy.Field()
    Contact_Name = scrapy.Field()
    EmailPrivate = scrapy.Field()
    Email = scrapy.Field()
    Social = scrapy.Field()
    Address = scrapy.Field()
    Additional_Info = scrapy.Field()
    Longitude = scrapy.Field()
    Latitude = scrapy.Field()
    Created = scrapy.Field()
    Updated = scrapy.Field()


class DutchieProductItem(scrapy.Item):
    Producer_ID = scrapy.Field()
    Page_URL = scrapy.Field()
    Brand = scrapy.Field()
    Name = scrapy.Field()
    SKU = scrapy.Field()
    Out_stock_status = scrapy.Field()
    Currency = scrapy.Field()
    ccc = scrapy.Field()
    Price = scrapy.Field()
    Manufacturer = scrapy.Field()
    Main_image = scrapy.Field()
    Description = scrapy.Field()
    Product_ID = scrapy.Field()
    Additional_Information = scrapy.Field()
    Meta_description = scrapy.Field()
    Meta_title = scrapy.Field()
    Old_Price = scrapy.Field()
    Equivalency_Weights = scrapy.Field()
    Quantity = scrapy.Field()
    Weight = scrapy.Field()
    Option = scrapy.Field()
    Option_type = scrapy.Field()
    Option_Value = scrapy.Field()
    Option_image = scrapy.Field()
    Option_price_prefix = scrapy.Field()
    Cat_tree_1_parent = scrapy.Field()
    Cat_tree_1_level_1 = scrapy.Field()
    Cat_tree_1_level_2 = scrapy.Field()
    Cat_tree_2_parent = scrapy.Field()
    Cat_tree_2_level_1 = scrapy.Field()
    Cat_tree_2_level_2 = scrapy.Field()
    Cat_tree_2_level_3 = scrapy.Field()
    Image_2 = scrapy.Field()
    Image_3 = scrapy.Field()
    Image_4 = scrapy.Field()
    Image_5 = scrapy.Field()
    Sort_order = scrapy.Field()
    Attribute_1 = scrapy.Field()
    Attribute_Value_1 = scrapy.Field()
    Attribute_2 = scrapy.Field()
    Attribute_value_2 = scrapy.Field()
    Attribute_3 = scrapy.Field()
    Attribute_value_3 = scrapy.Field()
    Attribute_4 = scrapy.Field()
    Attribute_value_4 = scrapy.Field()
    Reviews = scrapy.Field()
    Review_link = scrapy.Field()
    Rating = scrapy.Field()