# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class WeedmapsStoreItem(scrapy.Item):
    producer_id = scrapy.Field()
    p_id = scrapy.Field()
    producer = scrapy.Field()
    description = scrapy.Field()
    link = scrapy.Field()
    sku = scrapy.Field()
    city = scrapy.Field()
    province = scrapy.Field()
    store_name = scrapy.Field()
    postal_code = scrapy.Field()
    long = scrapy.Field()
    lat = scrapy.Field()
    ccc = scrapy.Field()
    page_url = scrapy.Field()
    active = scrapy.Field()
    main_image = scrapy.Field()
    image_2 = scrapy.Field()
    image_3 = scrapy.Field()
    image_4 = scrapy.Field()
    image_5 = scrapy.Field()
    type = scrapy.Field()
    license_type = scrapy.Field()
    date_licensed = scrapy.Field()
    phone = scrapy.Field()
    phone_2 = scrapy.Field()
    contact_name = scrapy.Field()
    email_private = scrapy.Field()
    email = scrapy.Field()
    social = scrapy.Field()
    full_address = scrapy.Field()
    address = scrapy.Field()
    additional_info = scrapy.Field()
    created = scrapy.Field()
    comment = scrapy.Field()
    updated = scrapy.Field()


class WeedmapsProductItem(scrapy.Item):
    page_url = scrapy.Field()
    brand = scrapy.Field()
    name = scrapy.Field()
    sku = scrapy.Field()
    out_stock_status = scrapy.Field()
    currency = scrapy.Field()
    ccc = scrapy.Field()
    price = scrapy.Field()
    manufacturer = scrapy.Field()
    main_image = scrapy.Field()
    description = scrapy.Field()
    product_id = scrapy.Field()
    additional_information = scrapy.Field()
    meta_description = scrapy.Field()
    meta_title = scrapy.Field()
    old_price = scrapy.Field()
    equivalent_weights = scrapy.Field()
    quantity = scrapy.Field()
    weight = scrapy.Field()
    option = scrapy.Field()
    option_type = scrapy.Field()
    option_value = scrapy.Field()
    option_image = scrapy.Field()
    option_price_prefix = scrapy.Field()
    cat_tree_1_parent = scrapy.Field()
    cat_tree_1_level_1 = scrapy.Field()
    cat_tree_1_level_2 = scrapy.Field()
    cat_tree_2_parent = scrapy.Field()
    cat_tree_2_level_1 = scrapy.Field()
    cat_tree_2_level_2 = scrapy.Field()
    cat_tree_2_level_3 = scrapy.Field()
    image_2 = scrapy.Field()
    image_3 = scrapy.Field()
    image_4 = scrapy.Field()
    image_5 = scrapy.Field()
    sort_order = scrapy.Field()
    attribute_1 = scrapy.Field()
    attribute_value_1 = scrapy.Field()
    attribute_2 = scrapy.Field()
    attribute_value_2 = scrapy.Field()
    attribute_3 = scrapy.Field()
    attribute_value_3 = scrapy.Field()
    attribute_4 = scrapy.Field()
    attribute_value_4 = scrapy.Field()
    reviews = scrapy.Field()
    review_link = scrapy.Field()
    rating = scrapy.Field()
    address = scrapy.Field()
    p_id = scrapy.Field()
